### PR TITLE
Remove awt.Rectangle

### PR DESCRIPTION
**Pull request by killpackoff**
Please remove the  java.awt.Rectangle to use the library on Android

### CODE REVIEW

**Comment by adam-arold** [comment]
Good idea, thanks for the PR. Where does this `Rectangle` come from? Did you copy it from somewhere or is this a custom implementation? I'm asking because if you just copied it from a well-established library there can be licensing issues.

**Comment by killpackoff** [comment]
it's from my arsenal. But I do not remember maybe there are parts from other libraries in it, it's better not to miss it. For me, Rectangle are not useful. I'm thinking you could take a trivial implementation without methods just a container or copy methods from the awt.Rectangle. if you need them.

**Comment by adam-arold** [comment]
Yep you are right. We don't need `Rectangle`, just the `intersects` and the `contains` methods. Do you have some unit tests for this class?

**Comment by killpackoff** [comment]
there are no tests for this class.

**Comment by adam-arold** [comment]
Can you add some tests to cover the functionality used by Zircon? You can look at an example [here](https://github.com/Hexworks/zircon/blob/master/src/test/kotlin/org/codetome/zircon/internal/behavior/impl/DefaultBoundableTest.kt).

**Comment by killpackoff** [comment]
I wrote the tests. Do I need to make another PR?

**Comment by killpackoff** [comment]
but these tests are in JUnit. I do not know Kotlin

**Comment by adam-arold** [comment]
Thanks, this will be fine. Can you revert `build.gradle` to its original state? Some lines were removed for some reason.

**Comment by killpackoff** [comment]
Of course. sorry, inadvertently missed

**Comment by adam-arold** [comment]
Cool I merged it! Can you use jitpack to pull the new version if I create a tag?

**Comment by killpackoff** [comment]
yes of course, just tell me the version number

**Comment by adam-arold** [comment]
okay, I'll create a tag soon, I'll let you know when it is ready

**Comment by adam-arold** [comment]
Try it with `2017.1.1-SNAPSHOT`

**Comment by killpackoff** [comment]
Thanks, I used the tag and it works. Now on android =)

**Comment by adam-arold** [comment]
Good to hear! Feel free to come up to our [Discord channel](https://discord.gg/NmrpGvT) if you have questions!

**Pull request merged**
